apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    service: {{ .Values.app.name }}
spec:
  ports:
  {{- range $k, $v := .Values.app.ports }}
  - port: {{ $k }}_{{ $v.port }}
    name: {{ $k }}_{{ $v.name }}
  { { - end } }
  selector:
    app: {{ .Values.app.name }}