apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name | squote }}
    service: {{ .Values.app.name | squote }}
spec:
  ports:
    {{- range $k, $v := .Values.app.ports }}
    - port: {{ $v.port }}
      name: {{ $v.name }}
    {{- end }}
  selector:
    app: {{ .Values.app.name | squote }}
    version: {{ .Values.app.version | squote }}